# Generated by Django 5.0 on 2023-12-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('role', models.CharField(choices=[('Barista', 'Barista'), ('Cashier', 'Cashier'), ('Server', 'Server'), ('Kitchen Staff', 'Kitchen Staff'), ('Cleaner', 'Cleaner')], max_length=20)),
                ('date_of_employement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
