# Generated by Django 5.0 on 2023-12-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='employee_name',
            new_name='staff_name',
        ),
    ]
