# Generated by Django 5.0 on 2023-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_employee_name_staff_staff_name'),
        ('orders', '0004_customer_remove_order_bill_remove_item_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_employement',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Barista', 'Barista'), ('manager', 'Manager'), ('Cashier', 'Cashier'), ('waiter', 'Waiter'), ('Kitchen Staff', 'Kitchen Staff')], max_length=255),
        ),
    ]
