# Generated by Django 5.0 on 2024-01-04 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('amount', models.IntegerField()),
                ('expired_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ثبت سفارش')),
                ('table_number', models.IntegerField(null=True, verbose_name='شماره میز')),
                ('order_detail', models.JSONField(default=dict)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('order_status', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد تخفیف')),
                ('order_number', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='شماره سفارش')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
