# Generated by Django 5.0 on 2024-01-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('percentage', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(editable=False, max_length=20)),
                ('updated_at', models.CharField(editable=False, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ثبت سفارش')),
                ('order_detail', models.JSONField(default=dict)),
                ('order_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('table_number', models.IntegerField(verbose_name=' شماره میز ')),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد تخفیف ')),
                ('final_price', models.CharField(max_length=255)),
                ('order_status', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
