# Generated by Django 5.0 on 2024-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
