# Generated by Django 5.0 on 2023-12-12 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='time',
        ),
        migrations.AddField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
