# Generated by Django 5.0 on 2023-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_bill_date_remove_bill_time_bill_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_cost',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
