# Generated by Django 5.0 on 2024-01-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_table_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آپدیت سفارش'),
        ),
    ]
