# Generated by Django 5.0 on 2024-01-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_options_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'سفارش محصولات'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
