# Generated by Django 5.0 on 2024-01-01 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_options_remove_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
