# Generated by Django 5.0 on 2024-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/%Y', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/%Y', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
