# Generated by Django 5.0 on 2023-12-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d/'),
        ),
    ]
