# Generated by Django 5.0 on 2023-12-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_item_item_status_alter_table_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'محصولات'},
        ),
    ]
