# Generated by Django 5.0 on 2023-12-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_alter_category_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی محصولات'},
        ),
    ]
