# Generated by Django 5.0 on 2023-12-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('logo_image', models.ImageField(upload_to='cafe/%Y', verbose_name='تصویر لوگو')),
                ('about_page_image', models.ImageField(upload_to='cafe/%Y', verbose_name='تصویر صفحه توضیحات')),
                ('about_page_description', models.TextField(verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name_plural': 'کافه',
            },
        ),
    ]
