# Generated by Django 5.0 on 2024-01-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_cafe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
