# Generated by Django 5.0 on 2024-01-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
